env:
  global:
  - CC_TEST_REPORTER_ID=d20eadb9183f9f1866657be5b5e47b4a2398ff1ea0be29fbd50a26a43ea98b62
  - REPORT_REPO_NAME=Travis-ci-code-coverage-reports
  - secure: M8jWqnatLYTny6mqLHZ7YbxINqpyCG0VPSotOLVMAAGkAranqcaeFYkfPUf72X/iIRGRmYWf4OFmnuzeE48jEtkWlvadiqqicO3/98gYa+peTljThM7L/nTFyUwQsqwE0HEya6rS/YRyl96B6u24M5GMpJPx+zgw1gTUgFe5vgR9HHA3IXB8+xMyEIqsZc0c8TLmJ4T53XVjaGHJ2louG8Yl2dR9Q8EY/SU8H2lYNg1wWoLQ5+lriwSVZ3NKUJG6l6vF2oZb15eBat4Vg1eLXfQ8xdE+YmndpIov1l3/0GtRoJNhdOVnzboso5V+fXUUDzs9oYcV7SzONzBOke5cyRZvdRnGB45Ou2RF8B6ciiUU5lQ7vsVoZmoI5TucfTFvL9fJkuGalvBCYTYopUwIqA8LRYFT/H8/syUsV6mnJWKjJjT7W7dz0jNTo2oucO944JtCD6mD7VnwgjLOq5qSkU1QHTwRtHcofo6L87F6BUXiOv+/T1qpd0iazpHyp7RveCc/Pvc6ZHjDY0t6eGHrp2E0hTjVxxb5AymNd+zi4sictOL77bIrUIBwcEUV9UQ6UeyaQAwYtyM4DvGkhka+rrcu1dhIS+8FpEcTuixUAdF4t7/aoFQ+2UR2Dw8nK6O7FdP2b067IbMFByfbnm8Ccz/hsUxEMZv3l2NW9taEFVA=
  matrix:
  - TESTFOLDER=models
  - TESTFOLDER=controllers
  - TESTFOLDER=helpers
  - TESTFOLDER=lib
language: ruby
dist: trusty
cache:
  bundler: true
  directories:
  - vendor/assets/components
rvm:
- 2.3.1
branches:
  only:
  - master
  - beta
  - v1_auto_deployment
before_install:
- uname -a
- lsb_release -a
- rvm list
- unset RAILS_ENV
- rvm rubygems current
- npm install -g bower
- bower install
- wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
- tar -xf geckodriver-v0.23.0-linux64.tar.gz
- sudo mv geckodriver /usr/local/bin/geckodriver
- geckodriver --version
- redis-server --version
- redis-server &
before_script:
- mysql -u root < db/grant_expertiza.sql
- cp config/database.yml.example config/database.yml
- cp config/secrets.yml.example config/secrets.yml
- export JAVA_HOME=/usr/lib/jvm/java-6-openjdk-amd64
- bundle install
- bundle exec rails db:setup
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.7.0-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- export DISPLAY=:99.0
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
- sleep 3
script:
- export DISPLAY=:99.0 && RUBYOPT=W0 bundle exec rspec spec/$TESTFOLDER 2> /dev/null
-
after_success:
- openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa
- bundle exec cap staging deploy
services:
- mysql
addons:
  firefox: latest
notifications:
  email:
    on_success: change
    on_failure: always
  webhooks:
    urls:
    - https://expertiza-travisci.herokuapp.com/?insertMode=update
